/* eslint-disable no-unused-vars */
export enum ContextMenuEnum {
  menuCliente = 'menuCliente',
  menuBanco = 'menuBanco',
  menuCentroCusto = 'menuCentroCusto',
  menuContaBancaria = 'menuContaBancaria',
  menuContasReceber = 'menuContasReceber',
  menuContasPagar = 'menuContasPagar',
  menuEstornarContasReceber = 'menuEstornarContasReceber',
  menuEstornarContasPagar = 'menuEstornarContasPagar',
  menuEmitirNFSContasReceber = 'menuEmitirNFSContasReceber',
  menuEmitirBorderoContasPagar = 'menuEmitirBorderoContasPagar',
  menuFornecedor = 'menuFornecedor',
  menuPlanoContas = 'menuPlanoContas',
  menuFuncionario = 'menuFuncionario',
  menuEmpresa = 'menuEmpresa',
  menuParametroCobranca = 'menuParametroCobranca',
  menuImposto = 'menuImposto',
  menuConciliacao = 'menuConciliacao',
  menuContrato = 'menuContrato',
  menuContratoResponsavel = 'menuContratoResponsavel',
  menuContratoImposto = 'menuContratoImposto',
  menuUsuario = 'menuUsuario',
  menuBi = 'menuBi',
  menuProjeto = 'menuProjeto',
  menuProjetoResponsavel = 'menuProjetoResponsavel',
  menuPrestacaoContas = 'menuPrestacaoContas',
  menuPrestacaoDespesa = 'menuPrestacaoDespesa',
  menuTimeSheet = 'menuTimeSheet',
}
