/* eslint-disable no-unused-vars */
export enum ModalEnum {
  baixarContasReceber = 'baixarContasReceber',
  baixarContasPagar = 'baixarContasPagar',
  estornarContasReceber = 'estornarContasReceber',
  estornarContasPagar = 'estornarContasPagar',

  gerarParcelasContrato= 'gerarParcelasContrato',

  emitirNFSContasReceber = 'emitirNFSContasReceber',
  emitirBorderoContasPagar = 'emitirBorderoContasPagar',

  renegociarContasReceber = 'renegociarContasReceber',
  renegociarContasPagar = 'renegociarContasPagar',

  createTimeSheet = 'createTimeSheet',
  createCliente = 'createCliente',
  createContaPagar = 'createContaPagar',
  createBanco = 'createBanco',
  createCentroCusto = 'createCentroCusto',
  createContaBancaria = 'createContaBancaria',
  createContasReceber = 'createContasReceber',
  createContasPagar = 'createContasPagar',
  createFornecedor = 'createFornecedor',
  createPlanoContas = 'createPlanoContas',
  createFuncionario = 'createFuncionario',
  createEmpresa = 'createEmpresa',
  createParametroCobranca = 'createParametroCobranca',
  createImposto = 'createImposto',
  createConciliacao = 'createConciliacao',
  createContrato = 'createContrato',
  createContratoResponsavel = 'createContratoResponsavel',
  createBi = 'createBi',
  createContratoImposto = 'createContratoImposto',
  createUsuario = 'createUsuario',
  createProjeto = 'createProjeto',
  createProjetoResponsavel = 'createProjetoResponsavel',
  createPrestacaoContas = 'createPrestacaoContas',
  createPrestacaoDespesa = 'createPrestacaoDespesa',

  filterTimeSheet = 'filterTimeSheet',
  filterContasReceber = 'filterContasReceber',
  filterContasPagar = 'filterContasPagar',
  filterBanco = 'filterBanco',
  filterCliente = 'filterCliente',
  filterFornecedor = 'filterFornecedor',
  filterCentroCusto = 'filterCentroCusto',
  filterPlanoContas = 'filterPlanoContas',
  filterContaBancaria = 'filterContaBancaria',
  filterParametroCobranca = 'filterParametroCobranca',
  filterImposto = 'filterImposto',
  filterConciliacao = 'filterConciliacao',
  filterContrato = 'filterContrato',
  filterContratoResponsavel = 'filterContratoResponsavel',
  filterContratoImposto = 'filterContratoImposto',
  filterUsuario = 'filterUsuario',
  filterProjeto = 'filterProjeto',
  filterProjetoResponsavel = 'filterProjetoResponsavel',
  filterPrestacaoContas = 'filterPrestacaoContas',
  filterPrestacaoDespesa = 'filterPrestacaoDespesa',
}
